### ISSUE TITLE
Merge in changes from U.S. Open Data

### ISSUE THREAD

**Issue by waldoj** [codeforamerica/OpenOpenDataCensus#1]
We've made [a whole raft of changes](https://github.com/opendata/Open-Data-Census/), mostly towards abstracting functionality and simplifying the Google Sheet. I'm going to merge all of those in, because rebasing and breaking those down into individual pull requests is implausible at this point.

**Comment by waldoj** [comment]
I created a new branch and then went and merged in all of the changes to master, with fd9f8e1, because I am history's greatest monster. ¯_(ツ)_/¯

**Comment by creade** [comment]
Haha nonsense! This is great, I'm glad this worked out!
